CompileFlags:
    Remove:
        - --diag_suppress*
        - --expt-relaxed-constexpr
        - --expt-extended-lambda
        - -forward-unknown-to-host-compiler
        - -gencode*
        - -Xcudafe
        - -Xcompiler*
